name: Daily Automated Update

on:
  schedule:

    - cron: '30 05 * * *' 

jobs:
  daily_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"


      - name: Create or update a file with current timestamp (23f2003980@ds.study.iitm.ac.in)
        run: |
          echo "Last automated update (23f2003980@ds.study.iitm.ac.in): $(date -uIs)" > automated_update.txt
          git add automated_update.txt

      - name: Commit changes
        run: |
          git commit -m "Automated daily activity update - $(date -uIs)"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
