name: Vercel App Pre-Deployment Checks

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  build_and_verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 23f2003980@ds.study.iitm.ac.in - Verify installed Python packages
        run: |
          echo "Checking that FastAPI, Uvicorn, and Pandas are installed."
          pip list | grep -E "fastapi|uvicorn|pandas" # This command will show if these are present

      
